pip install torch
pip install torchvision
pip install einops
pip install numpy==1.22.4
pip install scikit-learn
pip install tqdm
pip install pyyaml
pip install torchtoolbox
pip install torchmetrics
pip install timm
pip install pandas
pip install nibabel
pip install imageio
pip install thop